# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='\u7b2c\u4e00\u4e2a\u53c2\u6570\u5199\u6ce8\u91ca\u66f4\u6539'),
        ),
    ]
